kind: pipeline
type: kubernetes

steps:
  - name: cordova-build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./cordova-build/Dockerfile
      tags: cordova-build
      context: ./cordova-build

  - name: frankenphp
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./frankenphp/Dockerfile
      tags: frankenphp
      context: ./frankenphp
      target: prod

  - name: frankenphp-dev
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./frankenphp/Dockerfile
      tags: frankenphp-dev
      context: ./frankenphp
      target: dev

  - name: freqtrade
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./freqtrade/Dockerfile
      tags: freqtrade
      context: ./freqtrade

  - name: guardian
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./guardian/Dockerfile
      tags: guardian
      context: ./guardian
      platforms:
        - linux/arm64

  - name: icecast
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./icecast/Dockerfile
      tags: icecast
      context: ./icecast
      platforms:
        - linux/arm64

  - name: node-tools
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./node-tools/Dockerfile
      tags: node-tools
      context: ./node-tools
      platforms:
        - linux/amd64
        - linux/arm64

  - name: prettier
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./prettier/Dockerfile
      tags: prettier
      context: ./prettier
      platforms:
        - linux/amd64
        - linux/arm64

  - name: rtmp
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: sgj0
      password:
        from_secret: DOCKER_PASSWORD
      repo: sgj0/${DRONE_REPO_NAME}
      dockerfile: ./rtmp/Dockerfile
      tags: rtmp
      context: ./rtmp
      platforms:
        - linux/amd64
        - linux/arm64
