FROM freqtradeorg/freqtrade:stable AS freqtrade

RUN pip install --upgrade pip ta

FROM freqtradeorg/freqtrade:stable_pi AS pi

RUN pip install --upgrade pip ta

FROM freqtradeorg/freqtrade:stable_freqai AS freqai

RUN pip install --upgrade pip ta
